# Generated by Django 5.1.7 on 2025-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_artist_alter_post_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(max_length=30, verbose_name='スラッグ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-posted_at',)},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0, max_length=40, verbose_name='スラッグ'),
            preserve_default=False,
        ),
    ]
