# Generated by Django 5.1.7 on 2025-04-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_alter_post_options_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('artist', 'song_title')},
        ),
    ]
